/* 
 * Central place for constants for our app
 */

var constants = {
    'homeURI': 'homeURI',
    'basicAuthFormattedCredentials': 'basicAuthFormattedCredentials',
    'currentLocation': 'currentLocation',
    'customReverse': 'customReverse',
    'currentObjectRef': 'currentObjectRef',
    'currentObjectCheckOutUri' :'currentObjectCheckOutUri',
    'currentObjectCancelCheckOutUri' :'currentObjectCancelCheckOutUri',
    'currentObjectCheckInUri': 'currentObjectCheckInUri',
    'currentObjectJsonRepresentation': 'currentObjectJsonRepresentation',
    'isCheckedOut': 'isCheckedOut',
    'linkRelationDelete': 'http://identifiers.emc.com/linkrel/delete',
    'linkRelationObjects': 'http://identifiers.emc.com/linkrel/objects',
    'linkRelationPrimaryContent': 'http://identifiers.emc.com/linkrel/primary-content',
    'linkRelationContents': 'contents',
    'linkRelationContentMedia': 'http://identifiers.emc.com/linkrel/content-media',
    'linkRelationRepositories': 'http://identifiers.emc.com/linkrel/repositories',
    'linkRelationDql': 'http://identifiers.emc.com/linkrel/dql',
    'linkRelationSearch':'http://identifiers.emc.com/linkrel/search',
    'linkRelationBatches': 'http://identifiers.emc.com/linkrel/batches',
    'linkRelationCheckout': 'http://identifiers.emc.com/linkrel/checkout',
    'linkRelationCheckedOut': 'http://identifiers.emc.com/linkrel/checked-out-objects',
    'linkRelationCheckInNextMajor': 'http://identifiers.emc.com/linkrel/checkin-next-major',
    'linkRelationCancelCheckOut': 'http://identifiers.emc.com/linkrel/cancel-checkout',
    'linkRelationContents': 'contents',
    'linkRelationAbout': 'about',
    'linkRelationSelf': 'self',
    'linkRelationParent': 'parent',
    'linkRelationIcon': 'icon',
    'dqlTemplate':'dqlTemplate',
    'checkedOutUri': 'checkedOutUri',
    'documentObjectType': 'dm_document',
    'folderObjectType': 'dm_folder',
    'cabinetObjectType': 'dm_cabinet',
    'versionDataUri': 'versionDataUri',
    'noPreviewReference': 'img/nopreview.jpg',
    'iconChevronRight': 'glyphicon glyphicon-chevron-right',
    'iconFile': 'glyphicon glyphicon-file',
    'iconBook': 'glyphicon glyphicon-book',
    'deleteEnabled': 'deleteEnabled',
    'documentStaticImage': 'img/document.png',
    'contentfulStaticImage': 'img/contentful.png',
    'repositoryStaticImage': 'img/i-repo.png',
    'userStaticImage': 'img/user.jpg',
    'groupStaticImage': 'img/group.jpg',
    'formatStaticImage': 'img/format.jpg',
    'relationStaticImage': 'img/relation.jpg',
    'typeStaticImage': 'img/typeSchema.png',
    'uknownStaticImage': 'img/unknown.png',
    'currentFolderResourceUri': 'currentFolderResourceUri',
    'currentFolderResourceName': 'currentFolderResourceName',
    'thumbnailSize': 'thumbnailSize',
    'defaultThumbnailSize': '40',
    'largeThumbnailSize': '100',
    'listViewActive': 'listViewActive',
    'breadCrumbs': 'breadCrumbs',
    'breadCrumbsHref': 'breadCrumbsHref',
    'pageModifierString': 'modifier:',
    'activeState': 'active',
    'smallIconView':'smallIcons',
    'largeIconView':'largeIcons',
    'listView':'listView',
    'currentViewType':'currentViewType',
    'maxStandardStringLength':'20',
    'maxShortStringLength':'10'
};

var querySelector = {
    'searchWithThumbnails':"SELECT r_object_id, object_name, r_modify_date, r_object_type FROM dm_document SEARCH DOCUMENT CONTAINS '"
};

var resourceType  = {
    'service':0,
    'repository':1,
    'collection':2,
    'object':3,
    'content':4,
    'renditions':5,
    'searchresults':6,
    'checkedout':7,
    'type':8,
    'batchableResources':9,
    'contentless':10,
    'contentful':11,
    'folder':12,
    'unknown':100
};

var viewType = {
    'largeIcons':0,
    'smallIcons':1,
    'listView':2
};

var formatMapper = {
    "afp" : "AFP",
    "ai" : "illustrator",
    "aifc" : "aiff-c",
    "asm" : "ptcasm",
    "au" : "audio",
    "bas" : "vbbas",
    "bk" : "mbook",
    "chm" : "htmlhelp",
    "cvs" : "canvas",
    "dar" : "DAR",
    "dcm" : "dicom",
    "dgn" : "ustn",
    "dll" : "win32shrlib",
    "docm" : "msw12me",
    "docx" : "msw12",
    "dot" : "msw6template",
    "dotm" : "msw12metemplate",
    "dotx" : "msw12template",
    "drw" : "ptcdrw",
    "dwg" : "acad",
    "dwt" : "mmdwt",
    "eclipseh" : "eclipsehelp",
    "fla" : "flash",
    "fm" : "filemakerpro",
    "fp3" : "filemakerpro3",
    "fp4" : "filemakerpro4",
    "frm" : "vbfrm",
    "hs" : "javahelp",
    "htm" : "html",
    "ics" : "icalendar",
    "incd" : "incopy3",
    "incx" : "incopy4",
    "indd" : "indesign2",
    "jp2" : "jpeg2000",
    "jpg" : "jpeg",
    "lbi" : "mmlbi",
    "mak" : "vbmak",
    "map" : "imagemap",
    "mdb" : "ms_access",
    "mde" : "ms_access8_mde",
    "mil" : "cals1",
    "mov" : "quicktime",
    "mp4" : "mpeg-4v",
    "mpc" : "msproject_calendar",
    "mpg" : "mpeg",
    "mpg2" : "mpeg2",
    "mpp" : "msproject",
    "mpv" : "msproject_view",
    "ov" : "cals2",
    "pct" : "pict",
    "pm6" : "pagemaker", 
    "pot" : "ppt8_template",
    "potm" : "ppt12metemplate",
    "potx" : "ppt12template",
    "ppsm" : "ppt12meslideshow",
    "ppsx" : "ppt12slideshow",
    "ppt" : "powerpoint",
    "pptm" : "ppt12me",
    "pptx" : "ppt12",
    "pre" : "freelance",
    "properties" : "property",
    "prt" : "ptcprt",
    "psd" : "photoshop",
    "qxd" : "quark",
    "rf10" : "rsrc10",
    "rf9" : "rsrc9",
    "rft" : "dca",
    "sam" : "amipro",
    "scm" : "scam",
    "sl" : "hpuxshrlib",
    "so" : "linuxshrlib",
    "tif" : "tiff",
    "txt" : "text",
    "wav" : "wave",
    "wk4" : "123w",
    "wpd" : "wp10+",
    "wri" : "winwrite",
    "xls" : "excel",
    "xlsb" : "excel12bbook",
    "xlsm" : "excel12mebook",
    "xlsx" : "excel12book",
    "xlt" : "excel8template",
    "xltm" : "excel12metemplate",
    "xltx" : "excel12template",
    "xlw" : "excel4book",
    "xtg" : "quark4_report"
};